require: rubocop-rspec

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'
Lint/EmptyClass:
  AllowComments: true
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Exclude:
    - 'script/xbmcize.rb'
    - 'script/rename_movies_for_plex.rb'
    - 'script/unidentifiable_files.rb'
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Metrics/AbcSize:
  Max: 200
Metrics/BlockLength:
  Max: 250
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Max: 200
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 50
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/DescribeSymbol:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Exclude:
    - 'spec/lib/mylist_data_spec.rb'
    - 'spec/lib/renamer/duplicate_resolver_spec.rb'
    - 'spec/lib/renamer/video_file_mover_spec.rb'
    - 'spec/lib/renamer/file_quality_spec.rb'
RSpec/ExpectActual:
  Exclude:
    - 'spec/lib/renamer/name_generator_spec.rb'
RSpec/FilePath:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - 'spec/lib/renamer/renamer_spec.rb'
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MultipleDescribes:
  Exclude:
    - 'spec/lib/renamer/file_quality_spec.rb'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/lib/renamer/video_file_mover_spec.rb'
    - 'spec/lib/renamer/file_quality_spec.rb'
    - 'spec/lib/renamer/duplicate_resolver_spec.rb'
    - 'spec/lib/mylist_data_spec.rb'
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/lib/renamer/duplicate_resolver_spec.rb'
    - 'spec/lib/renamer/renamer_spec.rb'
RSpec/NamedSubject:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
RSpec/SpecFilePathFormat:
  CustomTransform:
    Cisqua:
      - ''
Style/ClassVars:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Exclude:
    - 'script/unidentifiable_files.rb'
Style/ParallelAssignment:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/SymbolArray:
  Exclude:
    - 'integration_spec/post_processor_spec.rb'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
AllCops:
  NewCops: enable
  Exclude:
    - 'external/**/*.rb'
    - 'net/**/*.rb'
    - 'bin/**/*'

